### ISSUE TITLE
Can't create a screenshot 

### ISSUE THREAD

**Issue by T8RIN** [IacobIonut01/Gallery#133]
The app can't be screenshoted

**Comment by T8RIN** [comment]
![Uploading Screenshot_20230812-182428_Галерея.png …]()

**Comment by T8RIN** [comment]
![Screenshot_20230812-182428_Галерея.png](https://github.com/IacobIonut01/Gallery/assets/52178347/899183d9-c0b5-4d07-87e5-dbd3b9070dba)

**Comment by IacobIonut01** [comment]
Open Gallery > Settings > Secure Mode (set to off)

**Comment by T8RIN** [comment]
Thanks!

**Comment by niktss** [comment]
Why is this the default though? It's just the user's images; if they wanted extra privacy because they're looking at something naughty, perhaps a "secure album" would work better, and also enable them to use all the features they are used to, like screenshots and peeking at things via the recent apps screen.
