### ISSUE TITLE
[Enhancement] Scroll bar

### ISSUE THREAD

**Issue by mizzunet** [IacobIonut01/Gallery#211]
**Is your feature request related to a problem? Please describe.**
Sort of. We could scroll better with a scrollbar than dragging the screen

**Describe the solution you'd like**
A scroll bar like this (taken from Google's Gallery app)
![ResizedImage_2023-10-30_11-01-47_9580](https://github.com/IacobIonut01/Gallery/assets/10193999/bbbb7312-701d-4878-a9ac-4e2728f3c114)

**Additional context**
I think it's better if the bottom navigation sheet sticky rather showing/hiding while scrolling. 
Thank you very much for such simple yet beautiful app. :)

**Comment by IacobIonut01** [comment]
Hi, first of all I don't want to be rude but just closed a feature request about the scroll bar because I've just pushed it in, you can give it a try by downloading the apk from the latest github actions build. It's best if we check closed features before creating a new one.

Also about the sticky navigation bar I made the choice to make it hide on scroll to give the user more space while scrolling to find the media easier

**Comment by mon-jai** [comment]
@IacobIonut01 Hi. I saw the mentioned commit.

But I just updated the app and there is no scroll bar in it. Reinstalling doesn't help too.

Version 2.0.0-20079

**Comment by IacobIonut01** [comment]
> @IacobIonut01 Hi. I saw the mentioned commit.
> 
> But I just updated the app and there is no scroll bar in it. Reinstalling doesn't help too.
> 
> Version 2.0.0-20079

Try to drag from the right vertically

**Comment by mon-jai** [comment]
Thanks.

Maybe making it visible all the time? (or add an option for it) It is not easy to find.

**Comment by IacobIonut01** [comment]
It's still an early implementation
