### ISSUE TITLE
[Enhancement] My tablet is not compatible T.T

### ISSUE THREAD

**Issue by SofiaRedmond** [IacobIonut01/Gallery#256]
(i tried using the latest artifact)

**Is your feature request related to a problem? Please describe.**
PlayStore tells me that is not available for my device and if i download the apk it tells me something like "it look like the package is not valid" 

**Describe the solution you'd like**
Make it compatible with my tablet please.

**Additional context**

Device: Lenovo Smart Tab M10 HD Wifi
Arq: ARMv8-A 64bits
OS: Android 10

![markup_1000080772.png](https://github.com/IacobIonut01/Gallery/assets/86848962/5240c8f0-5771-4ac4-b62d-bcdef30b7e26)

![markup_1000080771.png](https://github.com/IacobIonut01/Gallery/assets/86848962/2753fccf-7e1b-4a55-b7af-f8ab7dc6aacc)

**Comment by IacobIonut01** [comment]
Android 11 is the minimum version required

**Comment by SofiaRedmond** [comment]
Can i ask why Android 11?

**Comment by IacobIonut01** [comment]
I'll create a tab in README because this question is already way too asked and answered.

Android 11 is the minimum android version required to keep all features of the Gallery like Trash-bin, most of the API used etc.

Reducing the android version would result in feature loss for under android 11 devices and would require lots of compatibility changes for the MediaStore API

**Comment by SofiaRedmond** [comment]
This question must be very frequent because, in my opinion, Android 11 is a very high version for the minimum requirement of an app that is so necessary for everyday use. My phone has Android 13 thanks to a custom ROM, otherwise it would still be on Android 10 and usually, the devices of people I know have Android 9/10.

I feel sad that such a good app didn't get more reach because of this compatibility detail.
