### ISSUE TITLE
[Enhancement] Move code to GitLab or Codeberg

### ISSUE THREAD

**Issue by julianfairfax** [IacobIonut01/Gallery#300]
## [Delete before submission] Please use the latest build from Github Actions (Artifacts)

**Is your feature request related to a problem? Please describe.**
GitHub is not an open source platform, and being owned by Microsoft makes it more of a danger to open source projects, rather than a help.

**Describe the solution you'd like**
It would be nice if the project's code were moved to GitLab or Codeberg.

**Comment by inferenceus** [comment]
> GitHub is not an open source platform

@julianfairfax I know this issue is old and has been closed, but I'd like to say that this statement isn't entirely accurate. You can't control what code Codeberg or GitLab runs, nor see that it's actually what is running there. Open source is irrelevant when it comes to other people's servers.

> being owned by Microsoft makes it more of a danger to open source projects

Being owned by someone or something is irrelevant. We're here talking now, and if something does happen, the project can be moved elsewhere. Who says Codeberg or GitLab won't change policy or go offline? Every platform poses a risk; being owned by Microsoft or Google etc doesn't make it worse.
