### ISSUE TITLE
[Enhancement] Exclude locations

### ISSUE THREAD

**Issue by Captn138** [IacobIonut01/Gallery#528]
**Is your feature request related to a problem? Please describe.**
Pictures from some locatio's appear in the gallery

**Describe the solution you'd like**
I would like to have an option where I can add paths that would be excluded from the gallery

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by machschnell** [comment]
If you click on third item of groups of pictures like icons that appear toward the bottom of the screen, you'll see an **Ignored** category. Here you can add albums to ignore using regular expressions or by selecting individual folders (probably implies subfolders, it's not clear from wording in the app).

Note: it would be easier for users if the **Music** folder could be excluded via a setting because it's a common need.

Also, in a way choosing the Ignore Albums is a setting and seemingly should be accessible from the Settings menu.
