### ISSUE TITLE
[Enhancement] Is this Gallery app still lightweight when it is 140MB?

### ISSUE THREAD

**Issue by Pentaphon** [IacobIonut01/Gallery#538]
What can be done about making this app smaller instead of the 140MB it has somehow ballooned to?

**Comment by IacobIonut01** [comment]
This has been already discussed many times and I will repeat it again:

- The app size has increased due to popular requests of supporting decoding specific image formats (JPEG-XL, HEIF, AVIF - oferring the same image decoding capabilities to all users, no matter what the android supports by default)
- The app size has increased because of the above reason and because the main app is the universal apk - which contains those libraries (native so's) for every available architecture (arm, arm64, x86, x86_64)
- YOU DON'T HAVE TO download and install the universal apk, just pick your phone arch's apk from the release section
- "But F-Droid only shows the 120+mb variant" - yes, it has been already discussed and fixed, the multiple variants will be available starting with the next stable release (nightly doesn't count)

**Comment by Pentaphon** [comment]
Fair enough. Closing.
