### ISSUE TITLE
10 sec. rewind

### ISSUE THREAD

**Issue by Wjxfi** [IacobIonut01/Gallery#57]
10 seconds rewind by double-pressing forward to the right of the pause and backward to the left of the pause
https://user-images.githubusercontent.com/113500363/235288448-50c893e5-d0c2-4ca2-810b-613d4bd1621e.mp4

**Comment by IacobIonut01** [comment]
I'll make sure it's added

**Comment by niktss** [comment]
I think the gallery UI should stay simple; if you need to be able to rewind, opening in an actual video player might be better suited for you. Or if we really want to provide a full video player in-app, it should be gated behind the "Open with..." option, so that "video player" features like gestures/playback controls/rewind don't have to compete for space with "gallery features" like favourite/share/edit. Otherwise the UI gets very busy.

**Comment by IacobIonut01** [comment]
Don't worry, I'm still going to add it, but currently I'm quite bussy
