### ISSUE TITLE
[Bug] Crash on tapping share button 

### ISSUE THREAD

**Issue by Sureshgorai25** [IacobIonut01/Gallery#62]
The app is crashing after tapping on the share button after opening any image from folders like camera, screenshot which r in sd card.
To recreate this issue :- Just open any folders which r in sd card like camera then open any image, and then tap on share button, app will b closed immediately or u will get a popup gallery is stopped working.
Device - Realme 3
Android version - A13, sdk33
Hope u will fix it, thanks

**Comment by subhashis-barad** [comment]
[Gallery.txt](https://github.com/IacobIonut01/Gallery/files/11366044/Gallery.txt)


Me facing too, here I captured logs, of this entire session. Hope this helps:)

**Comment by Sureshgorai25** [comment]
Thanks for confirming

**Comment by IacobIonut01** [comment]
I'll check on my end and come up with a fix soon

**Comment by Sureshgorai25** [comment]
Did u check?
When can we expect a fix?

**Comment by Sureshgorai25** [comment]
Since it's a major issue and u r not fixing it we have no choice left, we shifted to a different gallery app.

**Comment by IacobIonut01** [comment]
1st, be familiar with the meaning of open source projects and their licenses. In this case the software is served as is, without any warranty whatsoever.
2nd, every issue will be addressed on their own terms. I have my own order of which things have more priority and this issue is there, but not on top. 
3rd, this is an open source project, which means outside contributions are always welcomed, feel free to fix yourself or wait properly until everything is done. The project as you may see is still in WIP stage.

Feel free to switch to any Gallery app you like.
